### ISSUE TITLE
A quick question for beginners

### ISSUE THREAD

**Issue by zhang-chi-debug** [openturns/otpod#15]
Hello, excuse me. I found the POD package you wrote on Github, and I ran with the OTPod case you wrote, but I ran into a little problem.
1. I can't save the picture as you said
2. I can't add legends when drawing the POD curve
I don't know if it's my fault.

**Comment by zhang-chi-debug** [comment]
> 你好，请见谅。我在Github上找到了你写的POD包，用你写的OTPod案例跑了一下，但是遇到了点小问题。
> 
> 1. 我不能像你说的那样保存图片
> 2. 绘制POD曲线时无法添加图例
>    不知道是不是我的错。

**Comment by zhang-chi-debug** [comment]
Hello, I have solved this problem, just change plot_kwargs to plot_kw in the _pod file. Thank you for the code package

**Comment by jschueller** [comment]
The code should be updated with plot_kw then.

**Comment by zhang-chi-debug** [comment]
Thank you very much for taking the time to answer my simple question.
：）

**Comment by jschueller** [comment]
done via 7d3ab20
