### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by zhang-chi-debug** [openturns/otpod#16]
Hello, I'm sorry to disturb you. I would like to ask that when I used Kriging model to do sensitivity analysis, he always gave a warning against the case you gave. At the same time, the graph I pointed out was different from the example you gave. In addition, it prompts me when I use the mixed polynomial model for analysis “Exception: The POD model does not contain, for the given defect interval, the wanted probability level.” It's confusing to me. If possible, I'd like to ask for your help。

**Comment by jschueller** [comment]
which example ?

**Comment by zhang-chi-debug** [comment]
Sobol Indices
http://openturns.github.io/otpod/master/examples/SobolIndices.html

**Comment by adumasphi** [comment]
This Exception happens because you ask a POD value that cannot be computed with respect to you data. Indeed the POD curve may not go from 0 to 1 depending on the data and the threshold. You should plot de POD, you will see the range of the probability that it is possible to compute.
