### ISSUE TITLE
I have a new question about quantile regression

### ISSUE THREAD

**Issue by zhang-chi-debug** [openturns/otpod#17]
Sorry to bother you, but I have a new question about your example of quantile regression.

You pointed out in the manual that setQyantile() function could be used to modify the quantile. I tried according to what you said, but the final POD curve did not change at all. Could you tell me what I did wrong?

**Comment by adumasphi** [comment]
The quantile regression requires to give the quantile value and for each value the defect size will be computed so that it is equal to the detection value. So it will just impact the number of points used to build the POD curve. The curve itself should not really change except if you provide really few quantile values or only high or low values.

**Comment by zhang-chi-debug** [comment]
Hello, thank you very much for taking the time to reply to me.

I tried to give only one quantile such as 0.1 or 0.9, but the final result of the plot did not change at all, and it seems that the A90/95 obtained by OLS for the same set of data is larger than that obtained by quantile regression, but the result I saw in one paper seems to be that quantile POD is more conservative than general linear regression POD. I understand that the quantile POD yields a90/95 larger than the general linear regression. I don't know if I misunderstood.

**Comment by adumasphi** [comment]
Did you run the method again after changing the quantile values ?

**Comment by zhang-chi-debug** [comment]
Yes, I did, but I got the same result, so I'm wondering if I changed it in the wrong place

**Comment by zhang-chi-debug** [comment]
I used the setQuantile() function to modify the quantile as you said in the manual. I wonder if I changed the quantile in the wrong place?

**Comment by adumasphi** [comment]
Can you provide your code because it is not possible to guess what could be wrong without it.

**Comment by zhang-chi-debug** [comment]
Can you tell me your E-mail? I will send it to you by E-mail

**Comment by zhang-chi-debug** [comment]
# import relevant module
import openturns as ot
import otpod
from time import time
import openturns as ot
import math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import xlrd
# 生成数据
data = xlrd.open_workbook('civa长5变深影响因素25f100.xls')
sh1 = data.sheet_by_index(0)
x = np.array(sh1.col_values(4))
y = np.array(sh1.col_values(5))
defects = ot.Sample([[v]for v in x])
signals = ot.Sample([[v]for v in y])
# 使用分位数（bootstrap）构建POD
# 信号检测阈值
detection = 1.2
# The POD with censored data actually builds a POD only on filtered data.
# A warning is diplayed in this case.
POD = otpod.QuantileRegressionPOD(defects, signals, detection,
                                  noiseThres=1.2, saturationThres=2.4)
# 用户定义分位数
# 输出默认分位数数值
print('Default quantile : ')
print(POD.getQuantile())
# 用户定义分位数（必须在0~1之间）
POD.setQuantile([0.5])
print('User-defined quantile : ')
print(POD.getQuantile())
# 运行分位数回归POD
# 利用bootstrap计算置信区间
# Due to the bootstrap technique used to compute the confidence
# interval, the run takes few minutes.
# A progress bar is displayed (can be removed using setVerbose(False))
t0 = time()
POD = otpod.QuantileRegressionPOD(defects, signals, detection,boxCox=True)
POD.run()
print('Computing time : {:0.2f} s'.format(time()-t0))
# 可以通过将模拟大小属性设置为另一个值来减少计算时间。然而，置信区间不太准确。
# 还可以减少分位数值的数量以节省时间
t0 = time()
PODsimulSize100 = otpod.QuantileRegressionPOD(defects, signals, detection,boxCox=True)
PODsimulSize100.setSimulationSize(100) # 计算置信区间迭代次数
PODsimulSize100.run()
print('Computing time : {:0.2f} s'.format(time()-t0))
# 计算缺陷大小
# Detection size at probability level 0.9
# and confidence level 0.95
# 在概率级别0.9和置信级别0.95的检测大小
print(POD.computeDetectionSize(0.9, 0.95))
# probability level 0.95 with confidence level 0.99
print(POD.computeDetectionSize(0.95, 0.99))
# 获取POD函数
# get the POD model
PODmodel = POD.getPODModel()
# get the POD model at the given confidence level
# 在给定的置信水平上获得POD模型
PODmodelCl95 = POD.getPODCLModel(0.95)
# # compute the probability of detection for a given defect value
# # 计算一个给定缺陷值的检测概率
# print('POD : {:0.3f}'.format(PODmodel([0.3])[0]))
# print('POD at level 0.95 : {:0.3f}'.format(PODmodelCl95([0.3])[0]))
# 计算给定分位数的R^2
print('Pseudo R2 for quantile 0.9 : {:0.3f}'.format(POD.getR2(0.9)))
print('Pseudo R2 for quantile 0.95 : {:0.3f}'.format(POD.getR2(0.95)))

# 绘制给定分位数的线性回归模型
fig, ax = POD.drawLinearModel(0.9)
fig.show()
# 绘制POD曲线
fig, ax = POD.drawPOD(probabilityLevel=0.9, confidenceLevel=0.95)
# The figure is saved in PODQuantReg.png
fig.show()

**Comment by adumasphi** [comment]
Ok I see what's wrong. In the example of the documentation, the quantile values are changed (cell [4]) to show it is possible but the evaluation of the POD curve does not use this modified object. The Python object named "POD" is redefined is the cell [5] without the change of the quantile.
As you use exactly this example for you case, it is the same. Try to pay attention of the variables name, so either you remove the line where the variable "POD" is redefined or you change the name.

**Comment by zhang-chi-debug** [comment]
I'm sorry to bother you again.I modified my code as you said, but still couldn't get the desired effect.
I even directly modified the package you provided, but the resulting a90/95 didn't have any change.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openturns/otpod"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 晚上9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openturns/otpod] I have a new question about quantile regression (Issue #17)





 
Ok I see what's wrong. In the example of the documentation, the quantile values are changed (cell [4]) to show it is possible but the evaluation of the POD curve does not use this modified object. The Python object named "POD" is redefined is the cell [5] without the change of the quantile.
 As you use exactly this example for you case, it is the same. Try to pay attention of the variables name, so either you remove the line where the variable "POD" is redefined or you change the name.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-chi-debug** [comment]
Hello, I'm sorry to bother you again. After I removed the definition of POD in [5] as you said, it reported an error, which said:The POD model at the confidence level does not contain, for the given defect interval, the wanted probability level.

**Comment by zhang-chi-debug** [comment]
I solved the above problem, thank you for your help. :)
